---
title: "tidytext- getData"
author: "Dominick J. Lemas"
date: "11/02/2021"
output: html_document

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick Lemas 
# Start Date:        Nov 02, 2021 
# Last Modified:     
# IRB:               UFHealth  
#                    
#
# version: R version 4.0.3 (2020-10-10)
# version: Rstudio version Version 1.3.1073 

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

#  (1) create tidytext tibble for downstream analysis. 


```


```{r, include=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************                Libraries                     *************** #
# **************************************************************************** #

library(plyr)
library(tidyverse)
library(stringr)
library(tidytext)
library(wordcloud)
library(ggplot2)
library(forcats)

```

```{r, warning=FALSE, echo=FALSE}

# DIRECTORY WITH FILES

# files <- list.files(path="~/nlp-perinatal/data/rda/", 
#                     pattern=".rda", 
#                     all.files=TRUE,
#                     full.names=TRUE)

files <- list.files(path="V:/FACULTY/DJLEMAS/NLP_Data/infantfeeding/v1/rda/", 
                    pattern=".rda", 
                    all.files=TRUE,
                    full.names=TRUE)
```

```{r, warning=FALSE, echo=FALSE}

# extract annotations
file_count=length(files)

# create empty tibble() for data
feeding <- tibble(
  note_id= character(),
  class = character(),
  note= character())

# loop through annotations
for(i in 1:file_count) {

  # loop through each annotation`
  file_index=files[[i]]

# EXTRACT DATA FROM XML

# import data
load(file=file_index) 

# note-id
note_id=unique(note[[3]]$note_id)

# class
tmp=nrow(note[[1]])
tmp2=first(note[[1]][[1]])
class=ifelse(tmp==0,"MISSING-CLASS",tmp2)

# notes
notes=note[[2]] 


# import to tibble
feeding[i,1]=note_id
feeding[i,2]=class
feeding[i,3]=notes 

}

# file name
file_name="feeding_nlp.rda"
data_directory=paste0("~/nlp-perinatal/data//tidy/") 
data_path=paste0(data_directory,file_name)

# export
feeding %>% save(feeding, file=data_path)

                              
```


