---
title: "tidytext- getData"
author: "Dominick J. Lemas"
date: "11/02/2021"
output: html_document

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick Lemas 
# Start Date:        Nov 02, 2021 
# Last Modified:     
# IRB:               UFHealth  
#                    
#
# version: R version 4.0.3 (2020-10-10)
# version: Rstudio version Version 1.3.1073 

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

#  (1) create tidytext tibble for downstream analysis. 


```


```{r, include=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************                Libraries                     *************** #
# **************************************************************************** #

library(plyr)
library(tidyverse)
library(stringr)
library(tidytext)
library(wordcloud)
library(ggplot2)
library(forcats)

```


```{r, warning=FALSE, echo=FALSE}

# DIRECTORY WITH FILES

files <- list.files(path="~/nlp-perinatal/data/tidy/", 
                    pattern=".rda", 
                    all.files=TRUE,
                    full.names=TRUE)

```

```{r, warning=FALSE, echo=FALSE}

file_index=files

# EXTRACT DATA FROM XML

# import data
load(file=file_index) 

# tidy
tidy_data <- feeding %>%
  unnest_tokens(word, note)

# remove stop-words
cleaned_books <- tidy_data %>%
  anti_join(get_stopwords())

# counts
cleaned_books %>%
  count(word, sort = TRUE)   
  
# word cloud
cleaned_books %>% count(word) %>%
  with(wordcloud(word, n, max.words = 100))
                              
```

```{r, warning=FALSE, echo=FALSE}

# Term frequency

book_words <- feeding %>%
  unnest_tokens(word, note) %>%
  count(class, word, sort = TRUE)
  
  total_words <- book_words %>% 
  group_by(class) %>% 
  summarize(total = sum(n))
  
  book_words <- left_join(book_words, total_words) %>%
                filter(class %in% c("NA","BREAST","BOTTLE"))
                

ggplot(book_words, aes(n/total, fill = class)) +
  geom_histogram(show.legend = FALSE) +
  xlim(NA, 0.0009) +
  facet_wrap(~class, ncol = 2, scales = "free_y")

# zips law
freq_by_rank <- book_words %>% 
  group_by(class) %>% 
  mutate(rank = row_number(), 
         `term frequency` = n/total) %>%
  ungroup()
  
  freq_by_rank %>% 
  ggplot(aes(rank, `term frequency`, color = class)) + 
  geom_line(size = 1.1, alpha = 0.8, show.legend = FALSE) + 
  scale_x_log10() +
  scale_y_log10()
  
# tf-IDF

book_tf_idf <- book_words %>%
  bind_tf_idf(word, class, n)
  
book_tf_idf %>%
  select(-total) %>%
  arrange(desc(tf_idf))

book_tf_idf %>%
  group_by(class) %>%
  slice_max(tf_idf, n = 15) %>%
  ungroup() %>%
  ggplot(aes(tf_idf, fct_reorder(word, tf_idf), fill = class)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~class, ncol = 2, scales = "free") +
  labs(x = "tf-idf", y = NULL)


```
