---
title: "cohort- builder- self harm"
author: "Dominick J. Lemas"
date: "11/01/2022"
output: html_document

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick Lemas 
# Start Date:        Nov 01, 2022 
# Last Modified:     
# IRB:               UFHealth  
#                    
#
# version: R version 4.0.3 (2020-10-10)
# version: Rstudio version Version 1.3.1073 

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

#  (1) Identify case/controls using ICD9/10 codes. 

```


```{r, include=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************                Libraries                     *************** #
# **************************************************************************** #

library(dplyr)
library(tidyverse)
library(stringr)
library(lubridate)

```

```{r, warning=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************               Import Data: 1:1 Wide
# **************************************************************************** #

dob_path="V:/FACULTY/DJLEMAS/EHR_Data/raw/READ_ONLY_DATASETS/10year_data/2021/dataset_09_2021/"
dob_file="baby_mom_at_birth_with_payer.csv"
dob_file_path=paste0(dob_path,dob_file)

# Import Files
births <- read_csv(dob_file_path, show_col_types = FALSE) %>%
  mutate(dob = mdy_hm(births$date_of_delivery)) %>%
  select(deidentified_baby_id,deidentified_mom_id,dob,-date_of_delivery,
         race_infant,ethnicity_infant,birth_weight,pediatric_gestational_age,
         sex,race_mom,ethnicity_mom,age_at_encounter_mom,payer_mom,admit_bmi) 

```

```{r, warning=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************               Import Data: 1:n Long
# **************************************************************************** #

code_path="V:/FACULTY/DJLEMAS/EHR_Data/raw/READ_ONLY_DATASETS/10year_data/2022/dataset_10_2022/"
code_file="selfharm_release.csv"
code_file_path=paste0(code_path,code_file)

# Import Files
codes <- read_csv(code_file_path, show_col_types = FALSE) %>%
  mutate(code_date=mdy(diagnosis_start_date)) %>%
  select(-diagnosis_start_date) %>%
  filter(diagnosis_type=="ENCOUNTER")

```

```{r, warning=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************               Format Data
# **************************************************************************** #

# intersection
match=intersect(births$deidentified_mom_id,codes$deidentified_mom_id)

# merge codes --> births. 
selfharm_births=left_join(births, codes) %>%
  mutate(match=!is.na(diagnosis_type)) %>%
  mutate(days2birth=as.double(difftime(code_date,dob,units ="days"))) %>%
  select(deidentified_mom_id,deidentified_baby_id,dob,code_date,days2birth,everything()) %>%
  mutate(prenatal=if_else(days2birth< -1,1,0),
         delivery=if_else(days2birth<1 & days2birth>-1, 1,0),
         postnatal=if_else(days2birth>1,1,0)) %>%
  mutate(current_delivery=if_else(between(days2birth, -365, 365),1,0)) 
  

unique(length(selfharm_births$deidentified_mom_id))
unique(length(selfharm_births$deidentified_baby_id))
unique(length(births$deidentified_baby_id))
unique(length(births$deidentified_mom_id))


```

```{r, warning=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************               Export Data
# **************************************************************************** #

# Export Data Files (sharedrive/ RDA)
#------------------------------------
file_name_rda=paste0("births_selfharm")
now <- Sys.time()
file_name_datestamp=paste0(file_name_rda, format(now, "_%Y%m%d.rda"))
selfharm_directory="V:/FACULTY/DJLEMAS/EHR_Data/processed/10_year_data/self_harm/"
data_path_rda=paste0(selfharm_directory,file_name_datestamp)
save(selfharm_births, file=data_path_rda)

# Export Data Files (sharedrive/ CSV)
#------------------------------------
file_name_csv=paste0("births_selfharm")
now <- Sys.time()
file_name_datestamp=paste0(file_name_csv, format(now, "_%Y%m%d.csv"))
selfharm_directory="V:/FACULTY/DJLEMAS/EHR_Data/processed/10_year_data/self_harm/"
data_path_csv=paste0(selfharm_directory,file_name_datestamp)
write_tsv(selfharm_births, path=data_path_csv, col_names=TRUE)

# Export Data Files (local/ RDA)
#------------------------------------
file_name_rda=paste0("births_selfharm")
now <- Sys.time()
file_name_datestamp=paste0(file_name_rda, format(now, "_%Y%m%d.rda"))
selfharm_directory="~/nlp-perinatal/data/processed/"
data_path_rda=paste0(selfharm_directory,file_name_datestamp)
save(selfharm_births, file=data_path_rda)

# Export Data Files (local/ CSV)
#------------------------------------
file_name_csv=paste0("births_selfharm")
now <- Sys.time()
file_name_datestamp=paste0(file_name_csv, format(now, "_%Y%m%d.csv"))
selfharm_directory="~/nlp-perinatal/data/processed/"
data_path_csv=paste0(selfharm_directory,file_name_datestamp)
write_tsv(selfharm_births, path=data_path_csv, col_names=TRUE)


```
