---
title: "teamtat-to-rda: infant feeding"
author: "Dominick J. Lemas"
date: "05/08/2023"
output: html_document

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas 
# Start Date:        October 03, 2022 
# Last Modified:     May 08, 2023 
# Title:             UFHealth Early Life Exposures and Pediatric Outcomes  
# IRB Study:         IRB Study #IRB201601899
# version: R version 4.2.1 (2022-06-23 ucrt) 
# version: RStudio 2022.07.1+554 

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

#  (1) Descriptive statistics on teamtat output. 
#  (2) Outputs for downstream analysis. 

```

```{r, include=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************                Libraries                     *************** #
# **************************************************************************** #

library(xml2)
library(XML) 
library(plyr)
library(tidyverse)
library(stringr)

```

```{r, warning=FALSE, echo=FALSE}

# DIRECTORY WITH FILES (LOCAL)

# files <- list.files(path="~/nlp-perinatal/data/xml/", 
#                     pattern=".xml", 
#                     all.files=TRUE,
#                     full.names=TRUE)

# DIRECTORY WITH FILES (UFRC)

data_input_path="V:/FACULTY/DJLEMAS/NLP_Data/infantfeeding/annotations/project1.2/v5/xml/"

files <- list.files(path=data_input_path,
                    pattern=".xml",
                    all.files=TRUE,
                    full.names=TRUE)

teamtat_project="project_1.2"
teamtat_version="v5"
now <- Sys.time()
analysis_date=paste0(format(now, "%Y%m%d"))

data_output_path="V:/FACULTY/DJLEMAS/NLP_Data/infantfeeding/annotations/project1.2/v5/rda/"

# data_output_path="~/mombaby-ehr-nlp/data/rda/"

```

```{r, warning=FALSE, echo=FALSE}

# extract annotations
file_count=length(files)

# loop through annotations
for(i in 1:file_count) {

annotation_metadata <- tibble(
  annotate_id = character(),
  class = character(),
  identifier = character(),
  annotator = character(),
  date = character(),
  offset = numeric(),
  length = numeric(),
  text = character()
  )
  
  # loop through each annotation`
  file_index=files[[i]]

# EXTRACT DATA FROM XML

# import data
x <- read_xml(file_index)

# extract teamtat & clinical-note ID
teamtat_id=xml_find_all(x, "//id") %>% xml_text(trim=TRUE) %>% as_tibble() %>% pull()
passage=xml_find_all(x, "//passage/text") %>% xml_text(trim=TRUE) %>% as_tibble()
note_id_all=last(passage$value)
note_id_tmp=str_replace_all(note_id_all, fixed(" "), "") 
note_id_tmp1=str_replace_all(note_id_tmp, fixed(":"), "_")
note_id=str_replace_all(note_id_tmp1, fixed(","), "_")

# extract annotations
clinical_note=passage[[1]][1]
annotate=xml_find_all(x, "//annotation") 


# loop through annotations
for(j in 1:length(annotate)) {

  # loop through each annotation`
  annotate_index=annotate[[j]]
  
  # ID
  annotate_id=xml_attr(annotate_index, "id")
  
  # ANNOTATION
  annotate_all=xml_find_all(annotate_index, "infon")
  attr=xml_attr(annotate_all, "key")
  text=xml_text(annotate_all,trim=TRUE)
  annotate_merge=as_tibble(cbind(attr,text))

  # LOCATION
  location_all=as_tibble(unlist(xml_attrs(xml_find_all(annotate_index, "location"))))
  offset=as.numeric(location_all[1,1])
  length=as.numeric(location_all[2,1])
  
  # TEXT
  text_all=xml_find_all(annotate_index, "text") %>% xml_text(trim=TRUE)

    # import to tibble
    annotation_metadata[j,1]=annotate_id
    annotation_metadata[j,2]=annotate_merge %>% filter(attr=="type") %>% select(text)
    annotation_metadata[j,3]=annotate_merge %>% filter(attr=="identifier") %>% select(text)
    annotation_metadata[j,4]=annotate_merge %>% filter(attr=="annotator") %>% select(text)
    annotation_metadata[j,5]=annotate_merge %>% filter(attr=="updated_at") %>% select(text)
    annotation_metadata[j,6]=offset 
    annotation_metadata[j,7]=length
    annotation_metadata[j,8]=text_all
   
  }

# populate data-frame

note_metadata=as_tibble(cbind(teamtat_id,note_id))

note_info = note_metadata %>%
  mutate(teamtat_project=teamtat_project,
         teamtat_version=teamtat_version,
         run_date=analysis_date)

# annotation output
class=annotation_metadata %>% filter(class=="FEED_CLASS") %>% select(text) %>% pull() 
clinical_note
note=list(class,note_info,clinical_note,annotation_metadata)

# file name
file_name=paste0(teamtat_id,".rda")

# path name
data_path=paste0(data_output_path,file_name)

# export
note %>% save(note, file=data_path)

# rm(note,annotate_index,annotation_metadata,class,data_final, feed_notes,
#    infon_df,infon_wider, note_info, note_metadata, note_status, passage, x, xml, xml_df)

}

# END FUNCTION
                              
```

