---
title: "teamtat- output"
author: "Dominick J. Lemas"
date: "10/25/2022"
output: html_document

---

```{r, include=FALSE}

# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas 
# Start Date:        October 03, 2022 
# Last Modified:     October 25, 2022 
# Title:             UFHealth Early Life Exposures and Pediatric Outcomes  
# IRB Study:         IRB Study #IRB201601899
# version: R version 4.2.1 (2022-06-23 ucrt) 
# version: RStudio 2022.07.1+554 

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

#  (1) Create file for downstream NLP analysis. 

```


```{r, include=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************                Libraries                     *************** #
# **************************************************************************** #

library(xml2)
library(XML) 
library(plyr)
library(tidyverse)
library(stringr)

```

```{r, warning=FALSE, echo=FALSE}

# DIRECTORY WITH FILES

# files <- list.files(path="~/nlp-perinatal/data/rda/", 
#                     pattern=".rda", 
#                     all.files=TRUE,
#                     full.names=TRUE)

files <- list.files(path="V:/FACULTY/DJLEMAS/NLP_Data/infantfeeding/v1/rda/", 
                    pattern=".rda", 
                    all.files=TRUE,
                    full.names=TRUE)

```

```{r, warning=FALSE, echo=FALSE}

# extract annotations
file_count=length(files)

# create empty tibble() for data
note_status <- tibble(
  note_id= character(),
  class_count = integer(),
  instance_count= integer(),
  class= character())

# loop through annotations
for(i in 1:file_count) {

# loop through each annotation`
file_index=files[[i]]

# EXTRACT DATA FROM RDA

# import data
load(file=file_index) 

# note-id
feed_notes=note[[3]] %>%
  mutate(class=as.factor(class),
         class_total=length(class))
note_id=unique(feed_notes$note_id)

# class_count
class_count=feed_notes %>%
  filter(class=="FEED_CLASS") %>%
  summarize(count=length(class)) %>% pull()

# instance_count
instance_count=feed_notes %>%
  filter(class=="FEED_INSTANCE") %>%
  summarize(count=length(class)) %>% pull()

# class
class=note[[1]]

# import to tibble
note_status[i,1]=note_id
note_status[i,2]=class_count
note_status[i,3]=instance_count 
note_status[i,4]=class


}  # END FUNCTION

# create part and note ids
note_status_tmp=note_status %>%
  mutate(note_id_tmp=note_id,
         note_id_tmp2=note_id) %>%
  separate(note_id_tmp,sep="_",c(NA, "part_id",NA,NA)) %>%
  separate(note_id_tmp2,sep="_",c(NA,NA,NA,"note_number"))

# class output
note_class= note_status_tmp %>%
  mutate(data_version="10_2022") %>%
  select(part_id,note_number,note_id,data_version,class)

# file name
file_name=paste0(note_class$data_version[1],"_infantfeed_class")
now <- Sys.time()
file_name_datestamp=paste0(file_name, format(now, "_%Y%m%d.csv"))

# data_directory=paste0("~/nlp-perinatal/data/processed/") 
data_directory=paste0("V:/FACULTY/DJLEMAS/NLP_Data/infantfeeding/v1/tidy/") 
data_path=paste0(data_directory,file_name_datestamp)

# export
  write_tsv(note_class, path=data_path, col_names=TRUE)

# END CODE BLOCK
                              
```



```{r, warning=FALSE, echo=FALSE}

# RAW TEXT

# extract annotations
file_count=length(files)

# create empty tibble() for data
note_raw <- tibble(
  note_id= character(),
  note_text= character())

# loop through annotations
for(i in 1:file_count) {

# loop through each annotation`
file_index=files[[i]]

# EXTRACT DATA FROM RDA

# import data
load(file=file_index) 

# note-id
feed_notes=note[[3]] %>%
  mutate(class=as.factor(class),
         class_total=length(class))
note_id=unique(feed_notes$note_id)

# note-text
raw=note[[2]]

# import to tibble
note_raw[i,1]=note_id
note_raw[i,2]=raw


}  # END FUNCTION

# file name
# paste0(format(now, "%Y%m%d_%H%M%S_"), "data_set.csv")
file_name=paste0("11_2022_infantfeed_text")
now <- Sys.time()
file_name_datestamp=paste0(file_name, format(now, "_%Y%m%d.csv"))

# data_directory=paste0("~/nlp-perinatal/data/processed/") 
data_directory=paste0("V:/FACULTY/DJLEMAS/NLP_Data/infantfeeding/v1/tidy/") 
data_path=paste0(data_directory,file_name_datestamp)

# export
  write_tsv(note_raw, path=data_path, col_names=TRUE)

# END CODE BLOCK
```


