---
title: "teamtat2tidy: infant feeding"
author: "Dominick J. Lemas"
date: "05/09/2023"
output: html_document

---

```{r, include=FALSE}

# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas 
# Start Date:        October  03, 2022 
# Last Modified:     May 09, 2023 
# Title:             UFHealth Early Life Exposures and Pediatric Outcomes  
# IRB Study:         IRB Study #IRB201601899
# version: R version 4.2.1 (2022-06-23 ucrt) 
# version: RStudio 2022.07.1+554 

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

#  (1) Create file for downstream NLP analysis. 

```


```{r, include=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************                Libraries                     *************** #
# **************************************************************************** #

library(xml2)
library(XML) 
library(dplyr)
library(tidyverse)
library(stringr)

```

```{r, warning=FALSE, echo=FALSE}

# DIRECTORY WITH FILES

# # project 1.2
# # -----------
# proj="project1.2"
# ver="v5"

# # project 2.2
# # -----------
# proj="project2.2"
# ver="v1"

# # project 3.2
# # -----------
# proj="project3.2"
# ver="v1"

# # project 4.2
# # -----------
# proj="project4.2"
# ver="v1"

# # project 5.2
# # -----------
# proj="project5.2"
# ver="v1"

# # project 6
# # -----------
# proj="project6"
# ver="v1"

# # project 7
# # -----------
# proj="project7"
# ver="v2"

# project 8
# -----------
proj="project8"
ver="v3"

# files <- list.files(path="~/nlp-perinatal/data/rda/", 
#                     pattern=".rda", 
#                     all.files=TRUE,
#                     full.names=TRUE)

data_input_path=paste0("V:/FACULTY/DJLEMAS/NLP_Data/infantfeeding/annotations/",proj,"/",ver,"/rda/")


files <- list.files(path=data_input_path, 
                    pattern=".rda", 
                    all.files=TRUE,
                    full.names=TRUE)


data_output_path=paste0("V:/FACULTY/DJLEMAS/NLP_Data/infantfeeding/annotations/",proj,"/",ver,"/tidy/")
data_output_path_project=paste0("V:/FACULTY/DJLEMAS/NLP_Data/infantfeeding/annotations/tidy/")

# create empty tibble() for data
note_status <- tibble(
  teamtat_id = character(),
  note_id = character(),
  teamtat_project = character(),
  teamtat_version = character(),
  run_date = character(),
  class_count = integer(),
  instance_count = integer(),
  class = character(),
  identifier = character())

```

```{r, warning=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************                CLASS-STRUCTURED              *************** #
# **************************************************************************** #

# extract annotations
file_count=length(files)

# loop through annotations
for(i in 1:file_count) {

# loop through each annotation`
file_index=files[[i]]

# EXTRACT DATA FROM RDA

# import data
load(file=file_index) 

# teamtat-id and note-id
feed_notes=note[[4]] %>%
  mutate(class=as.factor(class),
         class_total=length(class))
teamtat_id=note[[2]][1] %>% pull()
note_id=note[[2]][2] %>% pull()
teamtat_project=note[[2]][3] %>% pull()
teamtat_version=note[[2]][4] %>% pull()
run_date=note[[2]][5] %>% pull()

# class_count
class_count=feed_notes %>%
  filter(class=="FEED_CLASS") %>%
  summarize(count=length(class)) %>% pull()

# instance_count
instance_count=feed_notes %>%
  filter(class=="FEED_INSTANCE") %>%
  summarize(count=length(class)) %>% pull()

# class
class=note[[1]]

# identifier
identifier=feed_notes %>%
  filter(class=="FEED_CLASS") %>%
  select(identifier) %>% pull() 

# text
text=note[[4]][8]

# import to tibble
note_status[i,1]=teamtat_id
note_status[i,2]=note_id
note_status[i,3]=teamtat_project
note_status[i,4]=teamtat_version 
note_status[i,5]=run_date
note_status[i,6]=class_count
note_status[i,7]=instance_count
note_status[i,8]=class
note_status[i,9]=identifier


}  # END FUNCTION

# create part and note ids
note_status_tmp=note_status %>%
  mutate(note_id_tmp=note_id,
         note_id_tmp2=note_id) %>%
  separate(note_id_tmp,sep="_",c(NA, "part_id",NA,NA)) %>%
  separate(note_id_tmp2,sep="_",c(NA,NA,NA,"note_number"))

note_status=note_status_tmp

# # file name
file_name=paste0(teamtat_project,"_infantfeed_class_tidy")
now <- Sys.time()
file_name_datestamp=paste0(file_name, format(now, "_%Y%m%d.csv"))

# export path- local
data_directory=data_output_path
data_path=paste0(data_directory,file_name_datestamp)
write_tsv(note_status, path=data_path, col_names=TRUE)

# export path- project
data_directory=data_output_path_project
data_path=paste0(data_directory,file_name_datestamp)
write_tsv(note_status, path=data_path, col_names=TRUE)

# END CODE BLOCK #1
                              
# **************************************************************************** #
# ***************                CLASS-RAW TEXT                *************** #
# **************************************************************************** #

# extract annotations
file_count=length(files)

# create empty tibble() for data
note_raw <- tibble(
  note_id= character(),
  note_text= character())

# loop through annotations
for(i in 1:file_count) {

# loop through each annotation`
file_index=files[[i]]

# EXTRACT DATA FROM RDA

# import data
load(file=file_index) 

# project-id
teamtat_project=note[[2]][3] %>% pull()

# note-id
feed_notes=note[[4]] %>%
  mutate(class=as.factor(class),
         class_total=length(class))
note_id=note[[2]][2]

# note-text
raw=note[[3]]

# import to tibble
note_raw[i,1]=note_id
note_raw[i,2]=raw

}  # END FUNCTION

# EXPORT RAW TEXT
#---------------
# file name
file_name=paste0(teamtat_project,"_infantfeed_class_text")
now <- Sys.time()
file_name_datestamp=paste0(file_name, format(now, "_%Y%m%d.csv"))

# path name- local
data_directory=data_output_path 
data_path_tsv=paste0(data_directory,file_name_datestamp)
write_tsv(note_raw, path=data_path_tsv, col_names=TRUE)

# path name- project
data_directory=data_output_path_project 
data_path_tsv=paste0(data_directory,file_name_datestamp)
write_tsv(note_raw, path=data_path_tsv, col_names=TRUE)
  
# EXPORT RDA OBJECT
#------------------
# file name
file_name=paste0(teamtat_project,"_infantfeed_class_tidytext")
now <- Sys.time()
file_name_datestamp=paste0(file_name, format(now, "_%Y%m%d.rda"))

# path name- local
data_directory=data_output_path 
data_path_rda=paste0(data_directory,file_name_datestamp)
save(note_raw, file=data_path_rda)

# path name- project
data_directory=data_output_path_project 
data_path_rda=paste0(data_directory,file_name_datestamp)
save(note_raw, file=data_path_rda)
  
# END CODE BLOCK #2


# **************************************************************************** #
# ***************                INSTANCE-STRUCTURED/RAW       *************** #
# **************************************************************************** #

# create empty list
my_list <- list() 

# identify "INSTANCE"
instance_files= note_status %>%
  filter(instance_count>0) %>%
  select(teamtat_id) %>% pull()

# path
instance_data_input_path=paste0("V:/FACULTY/DJLEMAS/NLP_Data/infantfeeding/annotations/",proj,"/",ver,"/rda/",instance_files,".rda")

# extract annotations
file_count=length(instance_data_input_path)

# loop through annotations
for(i in 1:file_count) {

# loop through each annotation`
file_index=instance_data_input_path[[i]]

# import data
load(file=file_index) 

# teamtat-id and note-id
feed_instance=note[[4]] %>%
  filter(class=="FEED_INSTANCE")

feed_instance$teamtat_id=note[[2]][1] %>% pull()
feed_instance$note_id=note[[2]][2] %>% pull()
feed_instance$teamtat_project=note[[2]][3] %>% pull()
feed_instance$teamtat_version=note[[2]][4] %>% pull()
feed_instance$run_date=note[[2]][5] %>% pull()

feed_instance_final=feed_instance %>%
  select(teamtat_id,note_id,teamtat_project,teamtat_version,run_date,everything())

my_list[[i]] <- feed_instance_final

}  # END FUNCTION

# note and key files
note_instance=bind_rows(my_list)

# instance text
# -------------
note_instance_text=note_instance %>%
  select(note_id,text)

# file name
file_name=paste0(teamtat_project,"_infantfeed_instance_text")
now <- Sys.time()
file_name_datestamp=paste0(file_name, format(now, "_%Y%m%d.csv"))

# path name -local
data_directory=data_output_path 
data_path=paste0(data_directory,file_name_datestamp)
write_tsv(note_instance_text, path=data_path, col_names=TRUE)

# path name -project
data_directory=data_output_path_project 
data_path=paste0(data_directory,file_name_datestamp)
write_tsv(note_instance_text, path=data_path, col_names=TRUE)

# instance class
# -------------
note_instance_class=note_instance %>%
  select(teamtat_id,	note_id,	teamtat_project,	teamtat_version,	run_date,	annotate_id,	class,	identifier)

# file name
file_name=paste0(teamtat_project,"_infantfeed_instance_tidy")
now <- Sys.time()
file_name_datestamp=paste0(file_name, format(now, "_%Y%m%d.csv"))

# path name- local
data_directory=data_output_path 
data_path=paste0(data_directory,file_name_datestamp)
write_tsv(note_instance_class, path=data_path, col_names=TRUE)

# path name- project
data_directory=data_output_path_project 
data_path=paste0(data_directory,file_name_datestamp)
write_tsv(note_instance_class, path=data_path, col_names=TRUE)

# EXPORT RDA OBJECT
#------------------
# file name
file_name=paste0(teamtat_project,"_infantfeed_instance_tidytext")
now <- Sys.time()
file_name_datestamp=paste0(file_name, format(now, "_%Y%m%d.rda"))

# path name- local
data_directory=data_output_path 
data_path_rda=paste0(data_directory,file_name_datestamp)
save(note_instance, file=data_path_rda)

# path name- project
data_directory=data_output_path_project 
data_path_rda=paste0(data_directory,file_name_datestamp)
save(note_instance, file=data_path_rda)
  
# END CODE BLOCK

```


